### PR TITLE
Enhancing Morphological Analysis with spaCy Pretraining

### PR DESCRIPTION
**Pull request by thomashacker**
## Description

This project explores the effectiveness of pretraining techniques on morphological analysis (morphologizer) by conducting experiments on multiple languages. The objective of this project is to demonstrate the benefits of pretraining word vectors using domain-specific data on the performance of the morphological analysis. We leverage the OSCAR dataset to pretrain our vectors for tok2vec and utilize the UD_Treebanks dataset to train a morphologizer component. We evaluate and compare the performance of different pretraining techniques and the performance of models without any pretraining.

### Types of change

New project

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [x] I ran the `update` scripts in the `.github` folder, and all the configs and docs are up-to-date.

### CODE REVIEW

**Comment by thomashacker** [comment]
This project was finished some time ago, but we wanted to publish it with a post about pretraining. However, we never had time to do the post due to other priorities. It would make more sense to publish the project first and work on the blog post later.

**Comment by adrianeboyd** [comment]
Very nice! I'm testing it out a bit looking at supporting floret vectors.

Because I was mainly looking at vectors, I was expecting to see a comparison for vectors vs. pretraining+vectors, but training with just vectors doesn't seem to be included?

**Comment by adrianeboyd** [comment]
There is annoying off-by-one naming for sure, argh.

**Comment by thomashacker** [comment]
I've added a workflow for training the morphologizer with only static vectors, this makes 5 different combinations (for every of the three languages):
- No pretraining, No static vectors
- Only static vectors
- Character Objective Pretraining
- Vector Objective Pretraining
- Transformer

I've ran all experiments for the English language with my GPU. Here are the results for future reference:
| Label | no_pretraining | static | character_objective | vector_objective | transformer |
| :----: | :----: | :----: | :----: | :----: | :----: |
| pos_acc | 0.90 (0.00) | 0.94 (0.04) | 0.90 (0.00) | 0.94 (0.04) | 0.97 (0.07) |
| morph_micro_p | 0.92 (0.00) | 0.96 (0.04) | 0.92 (0.00) | 0.96 (0.04) | 0.98 (0.06) |
| morph_micro_f | 0.91 (0.00) | 0.95 (0.04) | 0.91 (-0.00) | 0.95 (0.04) | 0.98 (0.06) |
| morph_micro_r | 0.90 (0.00) | 0.95 (0.04) | 0.90 (-0.00) | 0.95 (0.04) | 0.97 (0.07) |
| PronType | 0.98 (0.00) | 0.99 (0.00) | 0.98 (0.00) | 0.99 (0.00) | 0.99 (0.01) |
| Number | 0.89 (0.00) | 0.95 (0.06) | 0.89 (-0.00) | 0.96 (0.06) | 0.98 (0.09) |
| Mood | 0.90 (0.00) | 0.94 (0.04) | 0.90 (0.00) | 0.93 (0.04) | 0.97 (0.08) |
| Tense | 0.88 (0.00) | 0.95 (0.07) | 0.88 (0.01) | 0.95 (0.07) | 0.97 (0.10) |
| VerbForm | 0.88 (0.00) | 0.93 (0.05) | 0.88 (0.00) | 0.93 (0.05) | 0.97 (0.09) |
| Gender | 0.98 (0.00) | 0.99 (0.00) | 0.98 (0.00) | 0.98 (0.00) | 0.98 (0.00) |
| Person | 0.97 (0.00) | 0.98 (0.01) | 0.97 (0.00) | 0.98 (0.01) | 0.99 (0.02) |
| Poss | 0.99 (0.00) | 1.00 (0.00) | 0.99 (0.00) | 1.00 (0.00) | 1.00 (0.00) |
| Definite | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) |
| Degree | 0.81 (0.00) | 0.92 (0.11) | 0.81 (-0.00) | 0.91 (0.10) | 0.96 (0.15) |
| Case | 0.96 (0.00) | 0.96 (0.00) | 0.96 (-0.00) | 0.96 (0.01) | 0.97 (0.01) |
| NumType | 0.90 (0.00) | 0.90 (-0.00) | 0.89 (-0.01) | 0.90 (-0.00) | 0.94 (0.04) |
| Voice | 0.64 (0.00) | 0.70 (0.05) | 0.62 (-0.03) | 0.70 (0.05) | 0.74 (0.10) |
| Typo | 0.00 (0.00) | 0.05 (0.05) | 0.00 (0.00) | 0.05 (0.05) | 0.34 (0.34) |
| Abbr | 0.13 (0.00) | 0.00 (-0.13) | 0.13 (0.00) | 0.35 (0.22) | 0.57 (0.44) |
| Foreign | 0.00 (0.00) | 0.00 (0.00) | 0.00 (0.00) | 0.00 (0.00) | 0.00 (0.00) |
| Reflex | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) | 1.00 (0.00) |
| speed | 38805.62 (0.00) | 40341.50 (1535.88) | 43037.18 (4231.56) | 40930.17 (2124.55) | 6519.16 (-32286.46) |

UD_English-EWT_training_graph

**Comment by adrianeboyd** [comment]
Interesting results! This makes it look like the pretraining doesn't help much, but English morphology is kind of boring, so I think we need to expand the evaluation to other languages/tasks before coming to much of a conclusion. In most of my quick (not careful) tests with floret vectors there did seem to be more differences in the final performance. We'd probably also want to test with vectors that are not trained on the same texts as are used for the pretraining.

**Comment by thomashacker** [comment]
I agree; I think more experiments in the future will be more helpful to see how much pretraining actually influences training. However, I think this project is still a great reference for users to see how to get the different pretraining objectives working, with the workflows being a good starting point. I hope this https://github.com/explosion/spaCy/pull/12459 `PR` will make the use of the project a bit easier by not manually adjusting the `model.bin` name in the `project.yml`.

**Comment by adrianeboyd** [comment]
This needs to be updated to require a newer version of spacy with the `model-last.bin` option for `spacy pretrain`.

**Comment by adrianeboyd** [comment]
Thanks again for your work @thomashacker!

**Pull request merged**
