### PR TITLE
GoEmotions disclaimer

### PR DESCRIPTION
**Pull request by koaning**
Figured I'd add a disclaimer. It's a great tutorial to show how a CSV works, but it's not a model I'd be comfortable putting into production.

### CODE REVIEW

**Comment by koaning** [comment]
I accidentally used `>` to overwrite the original README. Sorry about that!

**Comment by adrianeboyd** [comment]
I'm not sure all the README generation works as intended in the first place. It seems to clobber when I try it out, so it might not be you.

**Comment by adrianeboyd** [comment]
Ah, fun, `smart-open` broke on Monday. This is fixed in all my various v3.x backports releases, so it will be fixed in spacy very soon.

**Review by polm — APPROVED** [review]
Looks good to me, thanks for adding this! 

Additionally, the README generation seems to work fine when I use the `.github/update_docs.py` script.

**Pull request merged**
