### PR TITLE
WIP update projects

### PR DESCRIPTION
**Pull request by svlandeg**
Updates to projects after recent `spacy-nightly` refactors.
Trying to get the CI go back to green.

### CODE REVIEW

**Comment by ines** [comment]
I think we shouldn't really have `spacy-nightly` itself as a requirement anywhere – that's likely just going to cause us problems down the line because the projects themselves are executed via spaCy already (and we now have a mechanism for specifying version dependencies if we need to: by setting `spacy_version` to a version range in the `project.yml`).

In the FastAPI project, the requirement was needed for the Docker setup, I think. We should probably add a note about that in the `requirements.txt`.

**Comment by svlandeg** [comment]
Quick status update:
- I think the failure for the "speed" project on Windows should be fixed with the encoding fix in https://github.com/explosion/spaCy/pull/6234
- The FastAPI & Emerson projects will fail until we've released new spacy-nightly models with the "strings.json" serialized

**Comment by ines** [comment]
Update: `test_textcat_goemotions_project` should pass with the latest small fix I made to spaCy.

**Comment by svlandeg** [comment]
Yay, green! 
I reviewed once more, and looks good to me.

**Pull request merged**
