### PR TITLE
Update Python version for CI to 3.9

### PR DESCRIPTION
**Pull request by polm**
## Description

This updates the CI Python version from 3.7 to 3.9 because 3.7 will reach end of life next year. 

### Types of change

chore

## Checklist

- [x] I confirm that I have the right to submit this contribution under the project's MIT license.
- [x] I ran the tests, and all new and existing tests passed.
- [ ] I ran the `update` scripts in the `.github` folder, and all the configs and docs are up-to-date.

### CODE REVIEW

**Review by svlandeg — COMMENTED** [review]
3.7 still has half a year to go until it reaches EOL, and we still have many users on 3.7, so I wouldn't remove it from the CI entirely. What we can do though, is for instance run 3.7 on Windows and 3.9 on Linux, so we test more broadly.

**Comment by rmitsch** [comment]
Sounds reasonable. Questions:
- Has this been discussed internally yet?
- Why 3.9 and not 3.8?

**Comment by svlandeg** [comment]
We could add MacOS for 3.8 :-)

**Comment by polm** [comment]
I don't think we've discussed this internally. My choice of 3.9 here was basically arbitrary.

I have no objection to having multiple versions of Python in the CI, though before this PR the tests are already just using one version, probably to keep test runtime down. I also do think it's reasonable to expect fewer issues related to Python version here than in the main spaCy repo, for example. 

I'll go ahead and change this to:

- 3.7 Win
- 3.8 OSX
- 3.9 Linux

**Comment by polm** [comment]
Well, this found our first error in the tests: `mapfile` isn't in the default bash on OSX. I'll work on fixing it...

**Comment by rmitsch** [comment]
Which tests did you run to ensure that the behavior of the modified script matches the existing one? Specifically, are tests rerun if changes are detected at the first directory level? Sorry, my bash-fu isn't good enough to see that right away.

**Comment by polm** [comment]
Thanks for mentioning that - I had tested changes in the top-level directory but had forgotten about the README files in the first-level directories, so it would have re-run in that case. I fixed that.

After the fix, the way the bash script works bit by bit is:

```
git diff ... | sed ... # this was already there
cut -f 1-2 -d/ # was being done later anyway, but gives the first two components, and any second slash is removed (there is at most one slash)
grep /. # This finds things with a slash followed by a character (must be a second-level directory)
sort -u # This filters any duplicates, like if `a/b` and `a/b/c` have modifications
```

I tested this by making modifications to files at the top, first, second, and third levels, including duplicates and non-duplicates.

**Pull request merged**
